version: '3.8'

services:
  neo4j:
    image: neo4j:5.10
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/test1234
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app-network

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=test1234
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
